### PR TITLE
Allow position to be set by WCS for TOAST imagesets

### PR DESCRIPTION
**Pull request by imbasimba**

### CODE REVIEW

**Comment by pkgw** [comment]
Can you explain a bit more about the motivation for this? Is this so that we can compute useful Place locations for images that aren't all-sky but are big enough to need TOASTing? When in TOAST mode, do the imageset-level settings like OffsetX, Rotation, etc. even do anything?

**Comment by imbasimba** [comment]
Of course! This change is indeed for the TOASTing of images that aren't all-sky, in particular https://github.com/WorldWideTelescope/toasty/pull/86. In these cases it seems reasonable to goto the location of the imageset. When adding any kind of imageset, including TOAST, the engine does read Center, Offset, Scale, and Size to determine the camera position. It only reads these values if the `goto` parameter is true, which is always is for layers added through pywwt. Rotation is not read though.

**Comment by pkgw** [comment]
Ah, yes. Well, for TOAST imagesets I think it would be good to simplify and normalize the WTML metadata as much as possible. I think we should force OffsetX = OffsetY = 0, and maybe there is a sensible normalization to apply to the Size/Scale parameters?

It would also be good to add a comment to the function here explaining why it's worthwhile to set these parameters on TOAST images even if they don't "need" them for basic display.

**Comment by imbasimba** [comment]
Aha, we are talking about just the properties close inside that if/else statement. Indeed you are 100% correct. In fact, not setting these properties for TOAST (i.e. offset = 0 etc.) results in a more correct pan by the engine. My bad :)

**Pull request merged**
